name: Build and Push .NET API to Harbor

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    env:
      DISCORD_CLIENT_ID: ${{secrets.DISCORD_CLIENT_ID}}
      DISCORD_CLIENT_SECRET: ${{secrets.DISCORD_CLIENT_SECRET}}
      TELEGRAM_TOKEN: ${{secrets.TELEGRAM_TOKEN}}
      API_KEY: ${{secrets.API_KEY}}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"

      # Create appsettings.json from template and secrets
      - name: Create appsettings.json
        run: |
          cat > api.veve.dev/appsettings.json << EOF
          {
            "Logging": {
              "LogLevel": {
                "Default": "Information",
                "Microsoft.AspNetCore": "Warning"
              }
            },
            "AllowedHosts": "localhost;*.veve.dev;veve.dev",
            "Discord": {
              "ClientId": "${{ secrets.DISCORD_CLIENT_ID }}",
              "Token": "${{ secrets.DISCORD_CLIENT_SECRET }}",
              "Prefix": [ "!" ]
            },
            "Telegram": {
              "Token": "${{ secrets.TELEGRAM_TOKEN }}"
            },
            "ApiKeyAuthentication": {
              "ApiKeyHeader": "X-Api-Key",
              "ApiKey": "${{ secrets.API_KEY }}"
            }
          }
          EOF

      # Get version from project file
      - name: Get Version
        id: get_version
        run: |
          VERSION=$(grep -oPm1 "(?<=<Version>)[^<]+" api.veve.dev/*.csproj || echo "1.0.0")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Prepare the Docker image
      - name: Log in to Harbor Registry
        uses: docker/login-action@v3
        with:
          registry: harbor.fayevr.dev
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build \
            --build-arg BUILD_CONFIGURATION=Release \
            -t harbor.fayevr.dev/veve/api.veve.dev:${{ env.VERSION }} \
            -t harbor.fayevr.dev/veve/api.veve.dev:latest \
            -f api.veve.dev/Dockerfile .

      # Push the Docker image to Harbor
      - name: Push Docker Image
        run: |
          docker push harbor.fayevr.dev/veve/api.veve.dev:${{ env.VERSION }}
          docker push harbor.fayevr.dev/veve/api.veve.dev:latest

      # Trigger deployment webhook
      - name: Trigger Deployment
        run: |
          curl https://manage.fayevr.dev/api/deploy/lF8FcOaudCvddpVBSYHDL
